#######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options:
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Esquema proyecto Utrecht  # The title of the book. Will be placed in the left navbar.
author                      : Antonio Otal  # The author of the book
copyright                   : "2021"  # Copyright year to be placed in the footer
logo                        : irimed.png  # A path to the book logo
